spring.application.name=nutri

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS}

app.google.client-id=${GOOGLE_CLIENT_ID}

app.security.allowed-origins=${ALLOWED_ORIGINS}
